function data = load_data(setorder,varargin)
data = [];
if setorder == 1 %第1组数据
    [data.RGV.time1step,data.RGV.time2step,data.RGV.time3step,...
        data.CNC.time1in1,data.CNC.time1in2,data.CNC.time2in2,...
        data.RGV.timeOddCNC,data.RGV.timeEvenCNC,data.RGV.timeclean] =...
        deal(20,33,46,560,400,378,28,31,25);
elseif setorder == 2 %第2组数据
    [data.RGV.time1step,data.RGV.time2step,data.RGV.time3step,...
        data.CNC.time1in1,data.CNC.time1in2,data.CNC.time2in2,...
        data.RGV.timeOddCNC,data.RGV.timeEvenCNC,data.RGV.timeclean]=...
        deal(23,41,59,580,280,500,30,35,30);
elseif setorder == 3 %第3组数据
    [data.RGV.time1step,data.RGV.time2step,data.RGV.time3step,...
        data.CNC.time1in1,data.CNC.time1in2,data.CNC.time2in2,...
        data.RGV.timeOddCNC,data.RGV.timeEvenCNC,data.RGV.timeclean]=...
        deal(18,41,59,580,280,500,30,35,30);
else % %自定义数据
    [data.RGV.time1step,data.RGV.time2step,data.RGV.time3step,...
        data.CNC.time1in1,data.CNC.time1in2,data.CNC.time2in2,...
        data.RGV.timeOddCNC,data.RGV.timeEvenCNC,data.RGV.timeclean]=...
        deal(varargin);
end
end